[package]
name = "pm"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.42"
homedir = "0.3.6"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
sha2 = "0.10.9"
